const flagData = [
    {_id: 'Fra1', fullName: 'French Republic', features: ['blue', 'white', 'red', 'three'], image: 'France_flag.png'},
    {_id: 'UK1', fullName: 'United Kingdom of Great Britain & Northern Ireland', features: ['blue', 'white', 'red', 'cross', 'saltire', 'jack'], image: 'UK_flag.png'},
    {_id: 'Ger1', fullName: 'Federal Republic of Germany', features: ['black', 'yellow', 'red', 'three'], image: 'Germany_flag.png'},
    {_id: 'Spa1', fullName: 'Kingdom of Spain', features: ['yellow', 'red', 'three', 'shield', 'animal'], image: 'Spain_flag.png'},
    {_id: 'Ita1', fullName: 'Italian Republic', features: ['green', 'white', 'red', 'three'], image: 'Italy_flag.png'},
    {_id: 'Ire1', fullName: 'Republic of Ireland', features: ['green', 'white', 'orange', 'three'], image: 'Rep_of_Ireland_flag.png'},
    {_id: 'Ukr1', fullName: 'Ukraine', features: ['blue', 'yellow', 'two'], image: 'Ukraine_flag.png'},
    {_id: 'Pol1', fullName: 'Republic of Poland', features: ['red', 'white', 'two'], image: 'Poland_flag.png'},
    {_id: 'Pat1', fullName: 'St Patrick (Ireland / Northern Ireland)', features: ['red', 'white', 'saltire'], image: "Saint_Patrick's_flag.png"},
    {_id: 'Uls2', fullName: 'Northern Ireland (limited official usage)', features: ['red', 'white', 'cross'], image: "Ulster_Banner.png"},
    {_id: 'Uls1', fullName: 'Ulster (historic province)', features: ['red', 'yellow', 'cross', 'shield'], image: "Ulster_old.png"},
    {_id: 'Sco1', fullName: 'Scotland', features: ['blue', 'white', 'saltire'], image: "Scotland_flag.png"},
    {_id: 'Cze1', fullName: 'Czech Republic', features: ['red', 'white', 'two', 'blue'], image: 'Czechia_flag.png'},
    {_id: 'Bos1', fullName: 'Bosnia & Herzogovina', features: ['yellow', 'blue', 'white', 'star'], image: 'Bosnia_&_Herzogovina_flag.png'},
    {_id: 'Wal1', fullName: 'Principality of Wales', features: ['red', 'white', 'green', 'animal'], image: 'Wales_flag.png'},
    {_id: 'Por1', fullName: 'Portuguese Republic', features: ['red', 'green', 'shield', 'yellow', 'blue'], image: 'Portugal_flag.png'},
    {_id: 'Aus1', fullName: 'Commonwealth of Australia', features: ['blue', 'white', 'jack', 'star'], image: 'Australia_flag.png'},
    {_id: 'New1', fullName: 'New Zealand', features: ['blue', 'white', 'jack', 'star', 'red'], image: 'NZ_flag.png'},
    {_id: 'Jap1', fullName: 'Japan', features: ['red', 'white', 'sun'], image: 'Japan_flag.png'},
    {_id: 'Arg1', fullName: 'Argentine Republic', features: ['blue', 'white', 'sun', 'yellow', 'three'], image: 'Argentina_flag.png'},
    {_id: 'Chi1', fullName: 'Republic of China', features: ['blue', 'white', 'sun', 'red'], image: 'China_flag.png'},
    {_id: 'Chi2', fullName: "People's Republic of China", features: ['yellow', 'star', 'red'], image: 'PRChina_flag.png'},
    {_id: 'Ban1', fullName: "People's Republic of Bangladesh", features: ['green', 'red'], image: 'Bangladesh_flag.png'},
    {_id: 'Egy1', fullName: 'Arab Republic of Egypt', features: ['black', 'white', 'red', 'animal', 'yellow', 'three'], image: 'Egypt_flag.png'},
    {_id: 'Syr1', fullName: 'Syrian Arab Republic', features: ['black', 'white', 'red', 'green', 'star', 'three'], image: 'Syria_flag.png'},
    {_id: 'Syr2', fullName: 'Syrian Interim Government', features: ['black', 'white', 'red', 'green', 'star', 'three'], image: 'Syria_alt_flag.png'},
    {_id: 'Equ2', fullName: 'Republic of Equatorial Guinea', features: ['blue', 'white', 'red', 'green', 'yellow', 'tree', 'star', 'three', 'shield'], image: 'Equatorial_G_flag.png'},
    {_id: 'Leb2', fullName: 'Lebanese Republic', features: ['white', 'red', 'green', 'tree', 'three'], image: 'Lebanon_flag.png'},
    {_id: 'Bel2', fullName: 'Belize', features: ['blue', 'white', 'red', 'green', 'yellow', 'tree', 'three', 'shield'], image: 'Belize_flag.png'},
]

export default flagData;
